[package]
name = "triangle"
version = "0.1.34"
authors = ["Roman Chumak <p4ymak@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/p4ymak/triangle"
description = "Struct for geometric triangles. Includes Barycentric-Cartesian transforms and stuff.."

[dependencies]
