[package]
name = "triangle"
version = "0.1.0"
authors = ["Roman Chumak <p4ymak@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Struct for geometric triangles. Includes Barycentric-Cartesian transforms and stuff.."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
